filebeat.inputs:
  - type: container
    encoding: utf-8
    format: auto
    exclude_lines: ["^EOF"]
    paths:
      - '/var/lib/docker/containers/*/*.log'


processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]

#output.elasticsearch: #whis worked fine
#  hosts: ["es-hot:9200"]
#  indices:
#    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

#output.console:
#  enabled: true

logging.json: true
logging.metrics.enabled: false
